import {
  pgTable,
  text,
  timestamp,
  uuid,
  integer,
  numeric,
  boolean,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { reportNotesTable } from "./reportNotes";

/**
 * report_note_rows — calculated detail rows that make up a note.
 *
 * Many notes (Personalkostnader, Materiella anläggningstillgångar, etc.) are
 * really tables of sub-amounts. Each row carries:
 *   - the row label as it should be displayed in the printed note
 *   - current/previous year amounts
 *   - the source accounts (BAS account ranges) used to derive the amount, so
 *     the user can drill down and see exactly which transactions feed it
 *   - whether the row was generated by a calculator or entered manually
 *
 * Numeric amounts are kept nullable because some rows are pure subtotals or
 * intentionally blank (for example "Of which to related parties: —").
 */
export const reportNoteRowsTable = pgTable(
  "report_note_rows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    noteId: uuid("note_id")
      .notNull()
      .references(() => reportNotesTable.id, { onDelete: "cascade" }),
    rowKey: text("row_key").notNull(),
    label: text("label").notNull(),
    currentYearAmount: numeric("current_year_amount", { precision: 18, scale: 2 }),
    previousYearAmount: numeric("previous_year_amount", { precision: 18, scale: 2 }),
    isSubtotal: boolean("is_subtotal").notNull().default(false),
    isManual: boolean("is_manual").notNull().default(false),
    sourceAccountRanges: jsonb("source_account_ranges"),
    sourceAccountIds: jsonb("source_account_ids"),
    calculationNote: text("calculation_note"),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    noteIdIdx: index("report_note_rows_note_id_idx").on(table.noteId),
  }),
);

export const insertReportNoteRowSchema = createInsertSchema(reportNoteRowsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type InsertReportNoteRow = z.infer<typeof insertReportNoteRowSchema>;
export type ReportNoteRow = typeof reportNoteRowsTable.$inferSelect;
